const ICONS={wood:'🌲',brick:'🧱',wheat:'🌾',sheep:'🐑',ore:'⛏'};
const TYPE_ICON={forest:'🌲',hills:'🧱',pasture:'🐑',fields:'🌾',mountains:'⛰',desert:'☀'};
let session=JSON.parse(localStorage.getItem('islands-online-session')||'null');
let state=null,source=null,buildMode=null,lastDiceSignature=null,diceOverlayTimer=null;
let mapView={x:0,y:0,scale:1},dragState=null,ignoreMapClick=false;
const $=selector=>document.querySelector(selector);
const svgNS='http://www.w3.org/2000/svg';

function message(text,error=false){$('#onlineNotice').textContent=text;$('#onlineNotice').style.color=error?'#b44b3b':'#47705c'}
async function request(url,options={}){
  const response=await fetch(url,{...options,headers:{'content-type':'application/json',...(session?{authorization:`Bearer ${session.token}`}:{}) ,...(options.headers||{})}});
  const data=await response.json();if(!response.ok)throw new Error(data.error||'通信に失敗しました');return data;
}
function saveSession(value){session=value;localStorage.setItem('islands-online-session',JSON.stringify(value));}
function showGame(){ $('#joinScreen').hidden=true;$('#gameScreen').hidden=false;$('#roomCode').textContent=session.roomCode;connect(); }

async function createRoom(){try{const result=await request('/api/rooms',{method:'POST',body:JSON.stringify({name:$('#onlineName').value,boardMode:$('#onlineBoard').value})});saveSession(result);showGame()}catch(e){$('#joinError').textContent=e.message}}
async function joinRoom(rejoin=false){try{const code=(rejoin?session.roomCode:$('#roomCodeInput').value).trim().toUpperCase();const result=await request(`/api/rooms/${code}/join`,{method:'POST',body:JSON.stringify(rejoin?{rejoinToken:session.token}:{name:$('#onlineName').value})});saveSession(result);showGame()}catch(e){$('#joinError').textContent=e.message}}
function connect(){if(source)source.close();source=new EventSource(`/api/rooms/${session.roomCode}/events?token=${encodeURIComponent(session.token)}`);source.addEventListener('state',event=>{state=JSON.parse(event.data);$('#connectionStatus').textContent='● 同期中';render()});source.onerror=()=>{$('#connectionStatus').textContent='再接続中…'};}
async function action(type,payload={}){try{await request(`/api/rooms/${session.roomCode}/action`,{method:'POST',body:JSON.stringify({type,payload})});message('')}catch(e){message(e.message,true)}}

function el(name,attrs={},text=''){const node=document.createElementNS(svgNS,name);Object.entries(attrs).forEach(([key,value])=>node.setAttribute(key,value));if(text)node.textContent=text;return node}
function hexPoints(x,y,size=64){return Array.from({length:6},(_,i)=>{const a=Math.PI/3*i;return `${x+size*Math.cos(a)},${y+size*Math.sin(a)}`}).join(' ')}
function canInitialSettlement(vertex){const g=state.game;if(g.buildings[vertex])return false;const adjacent=g.edges.filter(e=>e.a===vertex||e.b===vertex).map(e=>e.a===vertex?e.b:e.a);return !adjacent.some(v=>g.buildings[v])}
function isAvailableVertex(vertex){const g=state.game;if(g.turn!==state.you)return false;if(g.stage==='setup-settlement')return canInitialSettlement(vertex);if(buildMode==='city')return g.buildings[vertex]?.player===state.you&&g.buildings[vertex].type==='settlement';if(buildMode!=='settlement'||g.buildings[vertex])return false;return canInitialSettlement(vertex)&&g.edges.some(e=>(e.a===vertex||e.b===vertex)&&g.roads[e.id]===state.you)}
function isAvailableEdge(edge){const g=state.game;if(g.turn!==state.you||g.roads[edge.id]!=null)return false;if(g.stage==='setup-road')return edge.a===g.setupVertex||edge.b===g.setupVertex;if(buildMode!=='road')return false;return [edge.a,edge.b].some(v=>g.buildings[v]?.player===state.you||g.edges.some(e=>(e.a===v||e.b===v)&&g.roads[e.id]===state.you))}

function renderBoard(){const g=state.game,svg=$('#onlineBoardSvg');svg.innerHTML='';g.tiles.forEach(tile=>{svg.append(el('polygon',{points:hexPoints(tile.x,tile.y),class:`tile ${tile.type}`}));svg.append(el('text',{x:tile.x,y:tile.y-17,'text-anchor':'middle','font-size':25},TYPE_ICON[tile.type]));if(tile.number){svg.append(el('circle',{cx:tile.x,cy:tile.y+15,r:18,class:'tile-number'}));svg.append(el('text',{x:tile.x,y:tile.y+21,'text-anchor':'middle','font-weight':800,fill:tile.number===6||tile.number===8?'#b44235':'#17372f'},tile.number))}});
  g.edges.forEach(edge=>{const a=g.vertices[edge.a],b=g.vertices[edge.b],owner=g.roads[edge.id];if(owner!=null){svg.append(el('line',{x1:a.x,y1:a.y,x2:b.x,y2:b.y,class:'road-outline'}));svg.append(el('line',{x1:a.x,y1:a.y,x2:b.x,y2:b.y,class:'road',style:`stroke:${state.players[owner].color};stroke-width:11px`}))}const hit=el('line',{x1:a.x,y1:a.y,x2:b.x,y2:b.y,class:'edge-hit'});if(isAvailableEdge(edge))hit.setAttribute('stroke','#ffd24f');hit.onclick=()=>!ignoreMapClick&&action('placeRoad',{edge:edge.id});svg.append(hit)});
  g.vertices.forEach(vertex=>{const building=g.buildings[vertex.id];if(building){const color=state.players[building.player].color;const points=building.type==='city'?`${vertex.x-12},${vertex.y+12} ${vertex.x-12},${vertex.y-5} ${vertex.x},${vertex.y-16} ${vertex.x+7},${vertex.y-8} ${vertex.x+15},${vertex.y-8} ${vertex.x+15},${vertex.y+12}`:`${vertex.x-13},${vertex.y+11} ${vertex.x-13},${vertex.y-4} ${vertex.x},${vertex.y-16} ${vertex.x+13},${vertex.y-4} ${vertex.x+13},${vertex.y+11}`;const piece=el('polygon',{points,class:'building',style:`fill:${color}`});piece.onclick=()=>!ignoreMapClick&&buildMode==='city'&&action('buildCity',{vertex:vertex.id});svg.append(piece)}else{const node=el('circle',{cx:vertex.x,cy:vertex.y,r:isAvailableVertex(vertex.id)?10:5,class:`node ${isAvailableVertex(vertex.id)?'available':''}`});node.onclick=()=>!ignoreMapClick&&isAvailableVertex(vertex.id)&&action('placeSettlement',{vertex:vertex.id});svg.append(node)}});
  const robber=g.tiles[g.robberTile];svg.append(el('circle',{cx:robber.x,cy:robber.y-34,r:13,class:'robber'}));
}

function renderPlayers(){const g=state.game;$('#onlinePlayers').innerHTML=state.players.map(p=>`<div class="online-player ${g&&g.turn===p.id?'active':''}"><i style="background:${p.color}"></i><span>${p.name}${p.id===state.you?' (あなた)':''}${p.isBot?' NPC':''}<small>${g?`${g.cardCounts[p.id]}枚`:p.connected?' 参加中':' 切断'}</small></span><b>${g?g.vp[p.id]:''} VP</b></div>`).join('');$('#tradeTo').innerHTML=state.players.filter(p=>p.id!==state.you).map(p=>`<option value="${p.id}">${p.name}</option>`).join('')}
function renderHand(){if(!state.game)return;$('#onlineHand').innerHTML=Object.entries(ICONS).map(([r,icon])=>`<div class="online-card">${icon}<b>${state.game.hand[r]}</b></div>`).join('')}
function renderOffers(){if(!state.game)return;$('#tradeOffers').innerHTML=state.game.offers.map(o=>{const incoming=o.to===state.you;return `<div class="offer">${state.players[o.from].name}: ${o.giveAmount}${ICONS[o.give]} ⇄ ${o.getAmount}${ICONS[o.get]}${incoming?`<br><button data-offer="${o.id}" data-accept="1">承認</button><button data-offer="${o.id}">拒否</button>`:''}</div>`}).join('');document.querySelectorAll('[data-offer]').forEach(btn=>btn.onclick=()=>action('respondTrade',{offerId:btn.dataset.offer,accept:btn.dataset.accept==='1'}))}
function showDiceOverlay(dice,player){const overlay=$('#diceOverlay');$('#diceOverlayPlayer').textContent=`${player} のダイス`;$('#diceOverlayA').textContent=dice[0];$('#diceOverlayB').textContent=dice[1];$('#diceOverlayTotal').textContent=`合計 ${dice[0]+dice[1]}`;overlay.classList.add('show');overlay.setAttribute('aria-hidden','false');clearTimeout(diceOverlayTimer);diceOverlayTimer=setTimeout(()=>{overlay.classList.remove('show');overlay.setAttribute('aria-hidden','true')},1250)}
function render(){renderPlayers();if(state.phase==='lobby'){$('#turnInfo').textContent=`参加者 ${state.players.length}/4`;$('#startOnlineBtn').hidden=state.host!==state.you;$('#startOnlineBtn').textContent=state.players.length<2?'NPCを追加して開始':'ゲーム開始';$('#lobbyHint').textContent=state.players.length<2?'友達を待つか、NPC3人を追加してすぐ遊べます。':'ホストがゲームを開始できます。';$('#onlineBoardSvg').innerHTML='';return}$('#startOnlineBtn').hidden=true;$('#lobbyHint').textContent='';const g=state.game;renderBoard();renderHand();renderOffers();const mine=g.turn===state.you;const stages={'setup-settlement':'開拓地を置いてください','setup-road':'街道を置いてください',roll:'ダイスを振ってください',build:'交換・建設ができます'};$('#turnInfo').textContent=`${state.players[g.turn].name}のターン · ${stages[g.stage]}`;$('#onlineDice').textContent=g.dice?g.dice.join(' + '):'—';const diceSignature=g.dice?`${g.round}:${g.turn}:${g.dice.join('-')}`:null;if(diceSignature&&diceSignature!==lastDiceSignature)showDiceOverlay(g.dice,state.players[g.turn].name);lastDiceSignature=diceSignature;$('#rollOnlineBtn').disabled=!mine||g.stage!=='roll';$('#endOnlineBtn').disabled=!mine||g.stage!=='build';['road','settlement','city'].forEach(mode=>$(`#${mode}ModeBtn`).disabled=!mine||g.stage!=='build');if(g.winner!=null)message(`${state.players[g.winner].name}の勝利！`)}

Object.entries(ICONS).forEach(([key,icon])=>{$('#onlineGive').add(new Option(icon,key));$('#onlineGet').add(new Option(icon,key))});$('#onlineGet').selectedIndex=1;
$('#createRoomBtn').onclick=createRoom;$('#joinRoomBtn').onclick=()=>joinRoom(false);$('#rejoinBtn').onclick=()=>joinRoom(true);$('#startOnlineBtn').onclick=async()=>{try{await request(`/api/rooms/${session.roomCode}/start`,{method:'POST',body:JSON.stringify({fillBots:state.players.length<2})})}catch(e){message(e.message,true)}};$('#rollOnlineBtn').onclick=()=>action('roll');$('#endOnlineBtn').onclick=()=>action('endTurn');
['road','settlement','city'].forEach(mode=>$(`#${mode}ModeBtn`).onclick=()=>{buildMode=buildMode===mode?null:mode;document.querySelectorAll('.actions button').forEach(b=>b.classList.remove('selected'));if(buildMode)$(`#${mode}ModeBtn`).classList.add('selected');renderBoard()});
$('#offerOnlineTrade').onclick=()=>action('offerTrade',{to:+$('#tradeTo').value,give:$('#onlineGive').value,giveAmount:+$('#onlineGiveAmount').value,get:$('#onlineGet').value,getAmount:+$('#onlineGetAmount').value});
function shareLink(){return `${location.origin}/online.html?room=${session.roomCode}`}
async function copyInvite(){const link=shareLink();try{await navigator.clipboard.writeText(link);message('招待リンクをコピーしました。友達に送って参加してもらえます')}catch{prompt('このリンクを友達に送ってください',link)}}
$('#copyRoomBtn').onclick=copyInvite;
if(session){$('#rejoinBtn').hidden=false;$('#rejoinBtn').textContent=`${session.roomCode}へ再参加`}
// 招待リンク（?room=CODE）で開いたときはルーム番号を自動入力
const invitedRoom=new URLSearchParams(location.search).get('room');
if(invitedRoom){const code=invitedRoom.trim().toUpperCase().slice(0,5);$('#roomCodeInput').value=code;$('#joinHint').textContent=`ルーム ${code} に参加します。名前を入れて「参加する」を押してください。`;$('#onlineName').focus()}

function applyMapView(){mapView.scale=Math.max(.6,Math.min(2.2,mapView.scale));$('#onlineBoardSvg').style.transform=`translate(${mapView.x}px,${mapView.y}px) scale(${mapView.scale})`}
function resetMap(){mapView={x:0,y:0,scale:1};applyMapView()}
const viewport=$('#boardViewport');
viewport.addEventListener('pointerdown',event=>{dragState={x:event.clientX,y:event.clientY,startX:mapView.x,startY:mapView.y,moved:false};viewport.setPointerCapture(event.pointerId);viewport.classList.add('dragging')});
viewport.addEventListener('pointermove',event=>{if(!dragState)return;const dx=event.clientX-dragState.x,dy=event.clientY-dragState.y;if(Math.hypot(dx,dy)>4){dragState.moved=true;ignoreMapClick=true}mapView.x=dragState.startX+dx;mapView.y=dragState.startY+dy;applyMapView()});
viewport.addEventListener('pointerup',event=>{const moved=dragState?.moved;dragState=null;viewport.classList.remove('dragging');try{viewport.releasePointerCapture(event.pointerId)}catch{}if(moved)setTimeout(()=>ignoreMapClick=false,80)});
viewport.addEventListener('wheel',event=>{event.preventDefault();mapView.scale+=event.deltaY<0?.12:-.12;applyMapView()},{passive:false});
$('#mapZoomIn').onclick=()=>{mapView.scale+=.15;applyMapView()};$('#mapZoomOut').onclick=()=>{mapView.scale-=.15;applyMapView()};$('#mapReset').onclick=resetMap;
